// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // Generated by `npm run codegen` -- don't lint someone else's output.
    ignores: ["dist/*", "src/generated/*"],
  }
]);
